// Generated by gencpp from file server_client/addInts.msg
// DO NOT EDIT!


#ifndef SERVER_CLIENT_MESSAGE_ADDINTS_H
#define SERVER_CLIENT_MESSAGE_ADDINTS_H

#include <ros/service_traits.h>


#include <server_client/addIntsRequest.h>
#include <server_client/addIntsResponse.h>


namespace server_client
{

struct addInts
{

typedef addIntsRequest Request;
typedef addIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct addInts
} // namespace server_client


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::server_client::addInts > {
  static const char* value()
  {
    return "4781436a0c2affec8025955a6041e481";
  }

  static const char* value(const ::server_client::addInts&) { return value(); }
};

template<>
struct DataType< ::server_client::addInts > {
  static const char* value()
  {
    return "server_client/addInts";
  }

  static const char* value(const ::server_client::addInts&) { return value(); }
};


// service_traits::MD5Sum< ::server_client::addIntsRequest> should match
// service_traits::MD5Sum< ::server_client::addInts >
template<>
struct MD5Sum< ::server_client::addIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::server_client::addInts >::value();
  }
  static const char* value(const ::server_client::addIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::server_client::addIntsRequest> should match
// service_traits::DataType< ::server_client::addInts >
template<>
struct DataType< ::server_client::addIntsRequest>
{
  static const char* value()
  {
    return DataType< ::server_client::addInts >::value();
  }
  static const char* value(const ::server_client::addIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::server_client::addIntsResponse> should match
// service_traits::MD5Sum< ::server_client::addInts >
template<>
struct MD5Sum< ::server_client::addIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::server_client::addInts >::value();
  }
  static const char* value(const ::server_client::addIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::server_client::addIntsResponse> should match
// service_traits::DataType< ::server_client::addInts >
template<>
struct DataType< ::server_client::addIntsResponse>
{
  static const char* value()
  {
    return DataType< ::server_client::addInts >::value();
  }
  static const char* value(const ::server_client::addIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERVER_CLIENT_MESSAGE_ADDINTS_H
