set(_CATKIN_CURRENT_PACKAGE "basePart")
set(basePart_VERSION "0.0.0")
set(basePart_MAINTAINER "ouyy <ouyy@todo.todo>")
set(basePart_PACKAGE_FORMAT "2")
set(basePart_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "urdf" "xacro")
set(basePart_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs" "urdf" "xacro")
set(basePart_BUILDTOOL_DEPENDS "catkin")
set(basePart_BUILDTOOL_EXPORT_DEPENDS )
set(basePart_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "urdf" "xacro")
set(basePart_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "urdf" "xacro")
set(basePart_TEST_DEPENDS )
set(basePart_DOC_DEPENDS )
set(basePart_URL_WEBSITE "")
set(basePart_URL_BUGTRACKER "")
set(basePart_URL_REPOSITORY "")
set(basePart_DEPRECATED "")